const LESSONS_DATA=[
    {
        title:"Introduction to the market",
        content:"The crypto market is relatively new, highly volatile, and has seen tremendous growth in recent years. It is a decentralized digital assets market where investors can buy and sell different type of cryptocurrencies, such as Bitcoin. The stock market, on the other hand, is an established market that has been in existence for centuries where publicly traded companies issue and sell shares of stock that represent ownership in the company. The value of the stock is influenced by factors such as earnings, market trends and global events. Both markets are subject to speculation and can be volatile, but they operate differently and have different underlying assets. Stocks are considered to be more stable than cryptocurrencies, but also tend to have lower potential returns.",
        url:"intro2.jpg"
    },
    {
        title:"Technical Analysis",
        content:"Cryptocurrency market and stock market operates differently, they both have different underlying assets, crypto is a digital currency while stock represents ownership in a company. Both markets are subject to speculation and can be volatile but stocks are considered more stable than crypto. Technical analysis is a method of evaluating securities by analyzing statistics generated by market activity, such as past prices and volume, it can be used in both crypto and stock market to evaluate historical performance and make predictions on future price movements. It is important to note that technical analysis is not always accurate and also that crypto market and stock market behavior is different.",
        url:"intro2.jpg"
    },
    {
        title:"Fundamental Analysis",
        content:"Fundamental analysis is a method of evaluating securities by analyzing underlying factors that affect the security's value. In the stock market, it focus on a company's financial health, management, and industry conditions by analyzing financial statements, assessing the management team and their track record and evaluating the overall health of the industry in which the company operates. In the crypto market, it's use is limited as many cryptocurrencies do not have traditional financials, assets or revenue streams. Instead it focuses on the technology behind the coin, the purpose or utility of the coin and the coin's adoption rate. While fundamental analysis can be a valuable tool in both markets, the approach and focus can be different and in the case of crypto market it's more important due to high failure rates.",
        url:"intro2.jpg"
    },
    {
        title:"Risk analysis",
        content:"Risk analysis is the process of assessing the potential risks and uncertainties associated with an investment, it's an important part of investment decision-making process. In the crypto market, risks include regulatory risks, cyber security risks and market liquidity risks. and in the stock market risks include market risk, industry risk, and company-specific risk. Additionally, company financials, earnings and management performance can also affect stock price and risk. It's important to conduct thorough research, understand the risks and potential rewards associated with different types of investments. Diversifying an investment portfolio can also help reduce risk.",
        url:"intro2.jpg"
    },
    {
        title:"Trading",
        content:"Trading is the process of buying and selling securities to make a profit. In the crypto market, it involves buying and selling different cryptocurrencies on a cryptocurrency exchange, and in the stock market, it involves buying and selling shares of stock on a stock exchange. Both can be done by individuals or through investment vehicles like ETFs or mutual funds. Both crypto and stock traders use technical and fundamental analysis, news and events to make informed trading decisions. However, crypto trading is different from stock trading, the crypto market is open 24/7, more volatile, with higher potential returns but also higher risks; while stock markets are typically closed on weekends, more regulated, transparent and have more liquidity but also lower potential returns.",
        url:"../../../../assets/lessons/intro2.jpg"
    },
    {
        title:"Investing",
        content:"Investing is the process of allocating resources such as money in the expectation of generating an income or profit. In the crypto market, it typically involves purchasing cryptocurrencies with the expectation that their value will increase over time. In the stock market, it typically involves purchasing shares of stock in publicly traded companies with the expectation that the value of the stock will increase over time. Both crypto and stock market investing can be done directly by individuals or through investment vehicles such as ETFs or mutual funds. They use a variety of tools and strategies to evaluate potential investments such as technical analysis, fundamental analysis and risk analysis. Crypto investing is a relatively new and highly volatile market, with less regulation and transparency compared to the stock market. It's important to conduct thorough research and understand the risks and potential rewards associated with different types of investments.",
        url:"intro2.jpg"
    },
    {
        title:"Portfolio management",
        content:"Portfolio management is the process of overseeing and managing a collection of assets, such as stocks, bonds, or cryptocurrencies, with the goal of maximizing returns while minimizing risk. In the crypto market, it typically involves buying and holding different cryptocurrencies and actively trading them. While in the stock market it involves buying and holding different stocks and actively trading them. Both crypto and stock markets portfolio management can be done by individuals or through professional portfolio management services. Diversification is an important aspect of portfolio management, as it can help to minimize risk by spreading investments across different assets. The goal of portfolio management is to create a balance of investments that will generate the best returns while minimizing risk, and to regularly monitor the portfolio and make adjustments as necessary.",
        url:"intro2.jpg"
    },
]

export default LESSONS_DATA