const QUIZ_DATA = [
    {
        lesson:'Introduction to the market',
        chapters:[
            {
                title:'Stock market',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Crypto',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Options',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Margins',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Derivatives',
                quizID:'Quiz-5',
                questions:[]
            },
            {
                title:'Futures',
                quizID:'Quiz-6',
                questions:[]
            },
        ]
    },
    {
        lesson:'Technical Analysis',
        chapters:[
            {
                title:'Introduction',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Basics',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'charting tools',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Charts(candlesticksm line, bar)',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Psychology',
                quizID:'Quiz-5',
                questions:[]
            },
            {
                title:'Volume',
                quizID:'Quiz-6',
                questions:[]
            },
            {
                title:'Patterns',
                quizID:'Quiz-7',
                questions:[]
            },
            {
                title:'Channels',
                quizID:'Quiz-8',
                questions:[]
            },
            {
                title:'Fibonacci',
                quizID:'Quiz-9',
                questions:[]
            },
            {
                title:'Harmoics',
                quizID:'Quiz-10',
                questions:[]
            },
            {
                title:'TPO',
                quizID:'Quiz-11',
                questions:[]
            },
            {
                title:'Footprints',
                quizID:'Quiz-12',
                questions:[]
            },
        ]
    },
    {
        lesson:'Fundamental Analysis',
        chapters:[
            {
                title:'Financial Statements ',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Revenue and Earnings',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Management and Leadership',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Competitive Advantage and Market Position',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Growth Prospects',
                quizID:'Quiz-5',
                questions:[]
            },
            {
                title:'Dividend Policy and Payout Ratio',
                quizID:'Quiz-6',
                questions:[]
            },
        ]
    },
    {
        lesson:'Risk Analysis',
        chapters:[
            {
                title:'Market Risk, Credit Risk, Liquidity Risk',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Managing Risk',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Risk-Reward Ratios',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Stop-Loss',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Volatility Measures',
                quizID:'Quiz-5',
                questions:[]
            },
            {
                title:'Diversification',
                quizID:'Quiz-6',
                questions:[]
            },
            {
                title:'Legal and Regulatory Risk',
                quizID:'Quiz-7',
                questions:[]
            },
            {
                title:'Quantitative Strategies',
                quizID:'Quiz-8',
                questions:[]
            },
        ]
    },
    {
        lesson:'Trading',
        chapters:[
            {
                title:'Trading Journal',
                quizID:'Quiz-1',
                questions:[]
            },{
                title:'Confluence',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Compounding',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Entry',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Exit',
                quizID:'Quiz-5',
                questions:[]
            },
        ]
    },
    {
        lesson:'Investing',
        chapters:[
            {
                title:'Trading Journal',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Confluence',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Compounding',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Entry',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Entry',
                quizID:'Quiz-5',
                questions:[]
            },
        ]
    },
    {
        lesson:'Portfolio management',
        chapters:[
            {
                title:'Trading Journal',
                quizID:'Quiz-1',
                questions:[]
            },
            {
                title:'Confluence',
                quizID:'Quiz-2',
                questions:[]
            },
            {
                title:'Compounding',
                quizID:'Quiz-3',
                questions:[]
            },
            {
                title:'Entry',
                quizID:'Quiz-4',
                questions:[]
            },
            {
                title:'Entry',
                quizID:'Quiz-5',
                questions:[]
            },
        ]
    }
]

export default QUIZ_DATA