const JOURNAL_DATA = [
    {
        conviction: "Strong",
        entryDate: "01/31/2023 00:01:00 AM",
        entryRate: "12300",
        exitDate: "01/02/2023 02:15:00 AM",
        exitRate: "12500",
        influence: "sdasd",
        issue: "fgdfg",
        points: "100",
        position: "Long",
        postTrade: "xfgxdfg",
        rewardRisk: "Risk",
        sell: "ervra",
        size: "300",
        strategy: "unknown",
        success: "success",
        ticker: "BTC",
        tradeName: "goku",
        journalEntryDate: "01/31/2023",
    },
    {
        conviction: "Strong",
        entryDate: "01/31/2023 00:01:00 AM",
        entryRate: "12300",
        exitDate: "01/02/2023 02:15:00 AM",
        exitRate: "12500",
        influence: "sdasd",
        issue: "fgdfg",
        points: "100",
        position: "Long",
        postTrade: "xfgxdfg",
        rewardRisk: "Risk",
        sell: "ervra",
        size: "100",
        strategy: "unknown",
        success: "success",
        ticker: "BTC",
        tradeName: "goku",
        journalEntryDate: "01/31/2023",
    },
    {
        conviction: "Strong",
        entryDate: "01/31/2023 00:01:00 AM",
        entryRate: "12300",
        exitDate: "01/02/2023 02:15:00 AM",
        exitRate: "12500",
        influence: "sdasd",
        issue: "fgdfg",
        points: "100",
        position: "Long",
        postTrade: "xfgxdfg",
        rewardRisk: "Risk",
        sell: "ervra",
        size: "400",
        strategy: "unknown",
        success: "success",
        ticker: "BTC",
        tradeName: "goku",
        journalEntryDate: "01/31/2023",
    },
    {
        conviction: "Strong",
        entryDate: "01/31/2023 00:01:00 AM",
        entryRate: "12300",
        exitDate: "01/02/2023 02:15:00 AM",
        exitRate: "12500",
        influence: "sdasd",
        issue: "fgdfg",
        points: "100",
        position: "Long",
        postTrade: "xfgxdfg",
        rewardRisk: "Risk",
        sell: "ervra",
        size: "500",
        strategy: "unknown",
        success: "success",
        ticker: "BTC",
        tradeName: "goku",
        journalEntryDate: "01/31/2023",
    },
    {
        conviction: "Strong",
        entryDate: "01/31/2023 00:01:00 AM",
        entryRate: "12300",
        exitDate: "01/02/2023 02:15:00 AM",
        exitRate: "12500",
        influence: "sdasd",
        issue: "fgdfg",
        points: "100",
        position: "Long",
        postTrade: "xfgxdfg",
        rewardRisk: "Risk",
        sell: "ervra",
        size: "600",
        strategy: "unknown",
        success: "success",
        ticker: "BTC",
        tradeName: "goku",
        journalEntryDate: "01/31/2023",
    }
]

export default JOURNAL_DATA;